# Generated by Django 6.0.4 on 2026-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_product",
            "0003_remove_product_is_active_remove_product_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care_guide",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="return_policy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
