# Generated by Django 6.0.4 on 2026-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0004_product_care_guide_product_return_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
