# Generated by Django 6.0.4 on 2026-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0005_variant_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='variants/'),
        ),
    ]
