# Generated by Django 6.0.4 on 2026-05-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
