# Generated by Django 6.0.4 on 2026-06-09 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_product",
            "0008_alter_product_options_alter_productimage_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="weight",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
