# Generated by Django 6.0.4 on 2026-06-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
    ]
