# Generated by Django 6.0.4 on 2026-06-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_products", "0002_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
