# Generated by Django 6.0.4 on 2026-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_products", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
