# Generated by Django 6.0.4 on 2026-06-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_products", "0005_review_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
