# Generated by Django 6.0.4 on 2026-05-19 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0008_alter_order_order_status_alter_order_return_status'),
        ('user_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='admin_orders.orderitem'),
        ),
    ]
