# Generated by Django 6.0.4 on 2026-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
