# Generated by Django 6.0.4 on 2026-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_orders", "0002_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
