# Generated by Django 6.0.4 on 2026-05-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_orders",
            "0009_order_razorpay_order_id_order_razorpay_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="transaction_id",
            field=models.CharField(default=False, editable=False, max_length=100),
        ),
    ]
