# Generated by Django 6.0.4 on 2026-05-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupon', '0002_coupon_description_alter_coupon_discount_value_and_more'),
        ('admin_orders', '0011_alter_wallettransaction_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_coupon.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
