# Generated by Django 6.0.4 on 2026-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_orders', '0012_remove_wallettransaction_transaction_id_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
