# Generated by Django 6.0.4 on 2026-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_category", "0002_category_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
