# Generated by Django 6.0.4 on 2026-05-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
