# Generated by Django 6.0.4 on 2026-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_category', '0004_alter_category_options_category_updated_at_and_more'),
        ('admin_offers', '0003_remove_offer_discount_percentage_offer_discount_type_and_more'),
        ('admin_product', '0008_alter_product_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type'], name='admin_offer_offer_t_12c108_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active'], name='admin_offer_is_acti_35689f_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['start_date'], name='admin_offer_start_d_0fff6b_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['end_date'], name='admin_offer_end_dat_4b04d7_idx'),
        ),
    ]
