# Generated by Django 6.0.4 on 2026-06-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_offers', '0005_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
