# Generated by Django 6.0.4 on 2026-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_auth", "0002_customuser_referral_code_customuser_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="show_referral_popup",
            field=models.BooleanField(default=False),
        ),
    ]
